name: Markdown Lint
on: [pull_request]

jobs:
  lint:
    runs-on: [ubuntu-latest]
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: linter
        uses: "articulate/actions-markdownlint@v1"
        with:
          config: .github/workflows/markdownlint-config.json
          files: '*.md'
          version: 0.28.1